In [1]:
from collections import Counter
from pathlib import Path
import pandas as pd

In [2]:
data_dir = Path("../data")
overview_file = data_dir / "bigtable_pangodesig.csv"
overview_df = pd.read_csv(overview_file)
pangos = overview_df.pango
len(pangos)

60

#### Independent recombination events

In [3]:
# Get the 1451 independent recombination events from the CovRecomb paper, and
# subset to the ones corresponding to the Pango X labels ("X" series).
# NOTE: No XBB.* or other X?.*
table_s4_url = "https://raw.githubusercontent.com/wuaipinglab/CovRecomb/refs/heads/main/CovRecomb-Global-Version/supplementary%20tables/TableS4.csv"
table_s4_df = pd.read_csv(table_s4_url)
table_s4_df = table_s4_df[table_s4_df.X_series.isin(pangos)].reset_index(drop=True)
table_s4_df.head(5)

,sample_id,collect_date,pango_lineage,lineage_X,lineage_Y,mutation_pattern,raw_p_value,adjusted_p_value,X_mutations,Y_mutations,shared_mutations,denovo_mutations,situation,region,country,Number_of_epidemic_recombinant,Geographical_distribution,X_series,Confidence_mean,breakpoints
0,hCoV-19/USA/CA-CDC-FG-008007/2021,2021/3/10,XB,B.1.631,B.1.634,YYYYYYYXXXXXXXXXY,1.780000e-39,1.440000e-36,22882_A/23604_A/23765_G/24442_T/24642_T/26158_...,7142_G/9614_G/9693_T/9754_C/11288_---------/15...,3037_T/14408_T/21615_G/21846_T/22036_C/23403_G...,1255_G/3688_T/3884_T/6633_T/15026_T/21057_T/23...,B.1.631_B.1.634,North America,USA,3332,USA_2611/Mexico_509/Spain_23/Honduras_55/Guate...,XB,0.9659,"28330-28910,16466-22882"
1,hCoV-19/Denmark/DCGC-322560/2022,2022/1/7,BA.2,BA.1.9,BA.2.23,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY,5.410000e-112,9.840000e-109,2832_G/5386_G/6513_---/8393_A,9866_T/10198_T/10447_A/11288_---------/12880_T...,3037_T/10029_T/10449_A/14408_T/18163_G/22578_A...,686_---------/3241_T/5924_A/27571_------------...,BA.1.9_BA.2.23,Europe,Denmark,2522,Denmark_22/United Kingdom_1767/Hong Kong_6/Ind...,XE,0.8517,8393-9866
2,hCoV-19/Venezuela/Dtt3630/2022,2022/1/22,BA.2,BA.1.1.7,BA.2.9*,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY,3.020000e-109,8.360000e-106,2470_T/2832_G/5386_G/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,3037_T/10029_T/10449_A/14408_T/18163_G/22578_A...,2441_A/6513_---/7081_T/13124_A/14838_T/15451_A...,BA.1.1.7_BA.2.9*,South America,Venezuela,427,Venezuela_4/Norway_11/USA_61/Costa Rica_144/De...,XAF,0.8135,8393-11288
3,hCoV-19/Denmark/DCGC-301091/2021,2021/12/30,XH,BA.1.9,BA.2.9*,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY,7.340000e-109,1.620000e-105,2832_G/5386_G/6513_---/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,3037_T/10029_T/10449_A/14408_T/18163_G/22578_A...,902_C/904_A/1244_A/28435_T,BA.1.9_BA.2.9*,Europe,Denmark,422,Denmark_187/Finland_151/Sweden_2/Belgium_6/Cze...,XH,0.8335,8393-11288
4,hCoV-19/USA/NJ-CDC-ASC210687738/2022,2022/1/29,XM,BA.1.1*,BA.2.23,XXXXXXXXXYYYYYYYYYYYYYYY,4.890000e-106,1.100000e-102,2470_T/2832_G/5386_G/6513_---/8393_A/11285_---...,21618_T/21633_---------/21987_A/22200_G/22688_...,3037_T/10029_T/10449_A/14408_T/18163_G/22578_A...,20343_C,BA.1.1*_BA.2.23,North America,USA,390,USA_5/Germany_220/Bahrain_1/Netherlands_17/Bel...,XM,0.9238,15240-21618

In [4]:
# Some Pango Xs have multiple events associated with them.
# There is typically one event that has the highest number of epidemic recombinants.
table_s4_df = table_s4_df[
    [
        "X_series",
        "lineage_X",
        "lineage_Y",
        "X_mutations",
        "Y_mutations",
        "mutation_pattern",
        #"situation",
        "breakpoints",
        "Number_of_epidemic_recombinant",
    ]
].sort_values(
    by=["X_series", "Number_of_epidemic_recombinant"],
    ascending=[True, False],
).reset_index(drop=True)
table_s4_df.head(5)

,X_series,lineage_X,lineage_Y,X_mutations,Y_mutations,mutation_pattern,breakpoints,Number_of_epidemic_recombinant
0,XA,B.1.1.7*,B.1.177.18,21765_------/21992_---/23063_T/23271_A/23604_A...,445_C/6286_T/10323_G/21255_C,YYYYXXXXXXXXXXXXXXXXXX,21255-21765,43
1,XAB,BA.1.1*,BA.2.31,2470_T/2832_G/5386_G/6513_---/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,XXXXXYYYYYYYYYYYYYYY,8393-11288,5
2,XAF,BA.1.1.7,BA.2.9*,2470_T/2832_G/5386_G/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY,8393-11288,427
3,XAF,BA.1.1.7,BA.2.9*,2470_T/2832_G/5386_G/8393_A,11288_---------/12880_T/15714_T/17410_T/21618_...,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYY,8393-11288,2
4,XAG,BA.1.1*,BA.2.9*,2470_T/2832_G/5386_G/6513_---,9534_T/9866_T/10198_T/10447_A/11288_---------/...,XXXXYYYYYYYYYYYYYYYYYYYYYY,6513-9534,17

In [5]:
def _get_breakpoints(mut_patt, left):
    pos = [x.split("_")[0] for x in mut_patt.split("/")]
    if left:
        return int(pos[0])
    return int(pos[-1])

In [6]:
data = []
for _, row in table_s4_df.iterrows():
    num_XY = row["mutation_pattern"].count("XY")
    num_YX = row["mutation_pattern"].count("YX")
    if num_XY + num_YX == 1:
        # NOTE: X and Y do not mean left parent and right parent, respectively.
        if num_XY == 1:
            parent_left_pango = row["lineage_X"]
            parent_right_pango = row["lineage_Y"]
            interval_left = _get_breakpoints(row["X_mutations"], left=False)
            interval_right = _get_breakpoints(row["Y_mutations"], left=True)
        else:
            parent_left_pango = row["lineage_Y"]
            parent_right_pango = row["lineage_X"]
            interval_left = _get_breakpoints(row["Y_mutations"], left=False)
            interval_right = _get_breakpoints(row["X_mutations"], left=True)
        data.append(
            {
                "pango": row["X_series"],
                "is_in_results": "TRUE",
                "type": "simple",
                "parent_left_pango": parent_left_pango,
                "parent_right_pango": parent_right_pango,
                "interval_left": str(interval_left),
                "interval_right": str(interval_right + 1),   # NOTE: Make right-exclusive.
                "num_epidemic_recombs": row["Number_of_epidemic_recombinant"],
            }
        )
    else:
        data.append(
            {
                "pango": row["X_series"],
                "is_in_results": "TRUE",
                "type": "complex",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "num_epidemic_recombs": row["Number_of_epidemic_recombinant"],
            }
        )
table_s4_df = pd.DataFrame(data)
table_s4_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,num_epidemic_recombs
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21766,43
1,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11289,5
2,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11289,427
3,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11289,2
4,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9535,17
5,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,43
6,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,15
7,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,6
8,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,2
9,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9345,12
10,XB,TRUE,complex,n/a,n/a,n/a,n/a,3332
11,XB,TRUE,complex,n/a,n/a,n/a,n/a,2
12,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22675,97
13,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22201,7
14,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22787,4
15,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,23020,3
16,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22675,2
17,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24621,268
18,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,22599,24621,3
19,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24621,2
20,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22600,376
21,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26530,8
22,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26530,134
23,XBJ,TRUE,simple,CM.2*,BA.5.2*,22332,26530,2
24,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27973,24
25,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9867,2522
26,XE,TRUE,simple,BA.1.9,BA.2.23,8393,11289,15
27,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289,422
28,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289,5
29,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289,3
30,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15715,73
31,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21619,390
32,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,35
33,XM,TRUE,simple,BA.1.1*,BA.2.23,13195,19956,24
34,XM,TRUE,simple,BA.1.1*,BA.2.23,22194,22689,8
35,XM,TRUE,simple,BA.1.1*,BA.2.23,22194,22689,4
36,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,3
37,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10450,13
38,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10450,2
39,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21619,142

In [7]:
# When there are multiple events associated with the same Pango X,
# get the event with the highest number of epidemic recombinants.
idx = table_s4_df.groupby('pango')['num_epidemic_recombs'].idxmax()
table_s4_df = table_s4_df.loc[idx].reset_index(drop=True)
table_s4_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,num_epidemic_recombs
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21766,43
1,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11289,5
2,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11289,427
3,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9535,17
4,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,43
5,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,2
6,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9345,12
7,XB,TRUE,complex,n/a,n/a,n/a,n/a,3332
8,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22675,97
9,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24621,268
10,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22600,376
11,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26530,8
12,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26530,134
13,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27973,24
14,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9867,2522
15,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289,422
16,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15715,73
17,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21619,390
18,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10450,13
19,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21619,142

#### Other putative recombination events

In [8]:
recomb_url = "https://raw.githubusercontent.com/wuaipinglab/CovRecomb/refs/heads/main/CovRecomb-Global-Version/putative_recombinants/putative%20recombinants.csv"
recomb_df = pd.read_csv(recomb_url)
recomb_df.columns

Index(['sample_id', 'collect_date', 'pango_lineage', 'lineage_X', 'lineage_Y',
       'mutation_pattern', 'raw_p_value', 'adjusted_p_value', 'X_mutations',
       'Y_mutations', 'shared_mutations', 'denovo_mutations', 'region',
       'country'],
      dtype='object')

In [9]:
# NOTE: pango_lineage is the Pango assigned to the sample (from GISAID).
for p in pangos:
    num_pango_lineage = sum(recomb_df.pango_lineage == p)
    #print(p, num_pango_lineage)

In [10]:
data = []
for p in pangos:
    num_simple = 0
    num_complex = 0
    recomb_counts = Counter()
    for _, row in recomb_df[
        # NOTE: Lumps together XBB.* and other X?.*
        (recomb_df.pango_lineage == p) | \
        (recomb_df.pango_lineage.str.startswith(p + "."))
    ].iterrows():
        num_XY = row["mutation_pattern"].count("XY")
        num_YX = row["mutation_pattern"].count("YX")
        if num_XY + num_YX == 1:
            num_simple += 1
            # NOTE: X and Y do not mean left parent and right parent, respectively.
            if num_XY == 1:
                parent_left_pango = row["lineage_X"]
                parent_right_pango = row["lineage_Y"]
                interval_left = _get_breakpoints(row["X_mutations"], left=False)
                interval_right = _get_breakpoints(row["Y_mutations"], left=True)
            else:
                parent_left_pango = row["lineage_Y"]
                parent_right_pango = row["lineage_X"]
                interval_left = _get_breakpoints(row["Y_mutations"], left=False)
                interval_right = _get_breakpoints(row["X_mutations"], left=True)
            recomb_counts[(parent_left_pango, parent_right_pango, interval_left, interval_right)] += 1
        else:
            num_complex += 1
    # Summarise results per Pango X.
    if num_simple + num_complex == 0:
        data.append(
            {
                "pango": p,
                "is_in_results": "FALSE",
                "type": "n/a",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "max_count": "n/a",
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
    elif num_simple >= num_complex:
        (
            most_common_parent_left,
            most_common_parent_right,
            most_common_interval_left,
            most_common_interval_right,
        ) = recomb_counts.most_common()[0][0]
        data.append(
            {
                "pango": p,
                "is_in_results": "TRUE",
                "type": "simple",
                "parent_left_pango": most_common_parent_left,
                "parent_right_pango": most_common_parent_right,
                "interval_left": str(most_common_interval_left),
                "interval_right": str(most_common_interval_right + 1),   # NOTE: Make right-exclusive.
                "max_count": max(recomb_counts.values()),    # Most common
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
    else:
        data.append(
            {
                "pango": p,
                "is_in_results": "TRUE",
                "type": "complex",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "max_count": "n/a",
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
recomb_df = pd.DataFrame(data)
recomb_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,max_count,num_simple,num_complex
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21766,43,43,0
1,XAA,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
2,XAB,TRUE,simple,BA.1.1*,BA.2.31,6513,9345,2,3,0
3,XAC,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
4,XAD,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
5,XAE,TRUE,simple,BA.2.3.16,B.1.1.322,27807,28878,3,3,0
6,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11289,277,292,0
7,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9345,24,38,0
8,XAH,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
9,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,n/a,1,76
10,XAK,TRUE,complex,n/a,n/a,n/a,n/a,n/a,0,28
11,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,94,118,5
12,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9345,11,12,0
13,XAN,TRUE,complex,n/a,n/a,n/a,n/a,n/a,6,13
14,XAP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
15,XAS,TRUE,simple,BA.5,BA.2.17,23075,25417,4,4,2
16,XAU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
17,XAV,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
18,XAY,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
19,XAZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
20,XB,TRUE,complex,n/a,n/a,n/a,n/a,n/a,52,3325
21,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22675,46928,51823,758
22,XBC,TRUE,complex,n/a,n/a,n/a,n/a,n/a,5,159
23,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24621,269,273,0
24,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22600,149,156,0
25,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26530,8,8,0
26,XBG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
27,XBH,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
28,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26530,124,134,0
29,XBK,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
30,XBL,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
31,XBM,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
32,XBN,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
33,XBP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
34,XBQ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
35,XBR,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
36,XBS,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
37,XBT,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
38,XBU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
39,XBW,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
40,XBZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
41,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27973,24,24,0
42,XCA,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
43,XCG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
44,XE,TRUE,simple,BA.1.9,BA.2.23,8393,11289,2210,2408,17
45,XF,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
46,XG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
47,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289,148,159,0
48,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15715,219,247,3
49,XL,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
50,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19956,273,464,6
51,XN,TRUE,simple,BA.2.3.16,BA.2.69,22688,22793,11,11,0
52,XP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
53,XQ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
54,XR,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
55,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10450,12,13,0
56,XU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
57,XW,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
58,XY,TRUE,simple,BA.1.1*,BA.2.9*,11537,12881,88,117,1
59,XZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0

#### Merging the results above

In [11]:
# NOTE: The breakpoint intervals have been adjusted to be right-exclusive.
data = []
for p in pangos:
    if any(table_s4_df.pango == p):
        row = table_s4_df[table_s4_df.pango == p]
    else:
        row = recomb_df[recomb_df.pango == p]
    data.append(
        {
            "pango": row["pango"].to_list()[0],
            "is_in_results": row["is_in_results"].to_list()[0],
            "type": row["type"].to_list()[0],
            "parent_left_pango": row["parent_left_pango"].to_list()[0],
            "parent_right_pango": row["parent_right_pango"].to_list()[0],
            "interval_left": row["interval_left"].to_list()[0],
            "interval_right": row["interval_right"].to_list()[0],
        }
    )
merged_df = pd.DataFrame(data)
merged_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21766
1,XAA,FALSE,n/a,n/a,n/a,n/a,n/a
2,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11289
3,XAC,FALSE,n/a,n/a,n/a,n/a,n/a
4,XAD,FALSE,n/a,n/a,n/a,n/a,n/a
5,XAE,TRUE,simple,BA.2.3.16,B.1.1.322,27807,28878
6,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11289
7,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9535
8,XAH,FALSE,n/a,n/a,n/a,n/a,n/a
9,XAJ,TRUE,complex,n/a,n/a,n/a,n/a
10,XAK,TRUE,complex,n/a,n/a,n/a,n/a
11,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19956
12,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9345
13,XAN,TRUE,complex,n/a,n/a,n/a,n/a
14,XAP,FALSE,n/a,n/a,n/a,n/a,n/a
15,XAS,TRUE,simple,BA.5,BA.2.17,23075,25417
16,XAU,FALSE,n/a,n/a,n/a,n/a,n/a
17,XAV,FALSE,n/a,n/a,n/a,n/a,n/a
18,XAY,FALSE,n/a,n/a,n/a,n/a,n/a
19,XAZ,FALSE,n/a,n/a,n/a,n/a,n/a
20,XB,TRUE,complex,n/a,n/a,n/a,n/a
21,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22675
22,XBC,TRUE,complex,n/a,n/a,n/a,n/a
23,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24621
24,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22600
25,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26530
26,XBG,FALSE,n/a,n/a,n/a,n/a,n/a
27,XBH,FALSE,n/a,n/a,n/a,n/a,n/a
28,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26530
29,XBK,FALSE,n/a,n/a,n/a,n/a,n/a
30,XBL,FALSE,n/a,n/a,n/a,n/a,n/a
31,XBM,FALSE,n/a,n/a,n/a,n/a,n/a
32,XBN,FALSE,n/a,n/a,n/a,n/a,n/a
33,XBP,FALSE,n/a,n/a,n/a,n/a,n/a
34,XBQ,FALSE,n/a,n/a,n/a,n/a,n/a
35,XBR,FALSE,n/a,n/a,n/a,n/a,n/a
36,XBS,FALSE,n/a,n/a,n/a,n/a,n/a
37,XBT,FALSE,n/a,n/a,n/a,n/a,n/a
38,XBU,FALSE,n/a,n/a,n/a,n/a,n/a
39,XBW,FALSE,n/a,n/a,n/a,n/a,n/a
40,XBZ,FALSE,n/a,n/a,n/a,n/a,n/a
41,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27973
42,XCA,FALSE,n/a,n/a,n/a,n/a,n/a
43,XCG,FALSE,n/a,n/a,n/a,n/a,n/a
44,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9867
45,XF,FALSE,n/a,n/a,n/a,n/a,n/a
46,XG,FALSE,n/a,n/a,n/a,n/a,n/a
47,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11289
48,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15715
49,XL,FALSE,n/a,n/a,n/a,n/a,n/a
50,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21619
51,XN,TRUE,simple,BA.2.3.16,BA.2.69,22688,22793
52,XP,FALSE,n/a,n/a,n/a,n/a,n/a
53,XQ,FALSE,n/a,n/a,n/a,n/a,n/a
54,XR,FALSE,n/a,n/a,n/a,n/a,n/a
55,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10450
56,XU,FALSE,n/a,n/a,n/a,n/a,n/a
57,XW,FALSE,n/a,n/a,n/a,n/a,n/a
58,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21619
59,XZ,FALSE,n/a,n/a,n/a,n/a,n/a

In [12]:
csv_file = data_dir / "bigtable_covrecomb.csv"
merged_df.to_csv(csv_file, sep=",", index=False)