# Time travellers in Viridian

In this notebook we do some brief analysis on the time travelling samples (those with a collection date that is much earlier than their true collection date) in the Viridian dataset.

This also provides a useful example of how to extract and manipulate metadata fields from the VCF Zarr encoding using Pandas.

In [1]:
import sc2ts

In [2]:
ds = sc2ts.Dataset("../data/viridian_mafft_2024-10-14_v1.vcz.zip")
ds

Dataset at ../data/viridian_mafft_2024-10-14_v1.vcz.zip with 4484157 samples, 29903 variants, and 30 metadata fields. See ds.metadata.field_descriptors() for a description of the fields.

In [3]:
ds.metadata.field_descriptors()

,dtype,description
field,,
Artic_primer_version,object,"If known, the ARTIC primer scheme from ENA met..."
Collection_date,object,collection_date from ENA metadata
Country,object,Country from ENA metadata. If ':' was in the e...
Date_tree,object,"A consensus date, using up 3 sources of data f..."
Date_tree_order,object,This helped define the order in which the samp...
Experiment,object,experiment_accession from ENA metadata
First_created,object,first_created from the ENA metadata
Genbank_N,int16,Number of Ns in the GenBank consensus sequence...
Genbank_accession,object,This is the GenBank accession of the assembly
Genbank_other_runs,object,Any other run accessions associated with the G...
Genbank_pangolin,object,Pangolin call from the GenBank consensus seque...
Genbank_scorpio,object,Scorpio call from the GenBank consensus sequen...
Genbank_tree_name,object,Name of the sample in the GenBank tree
In_Viridian_tree,bool,'T' or 'F' to indicate if the sample is in the...
In_intersection,bool,'T' or 'F' to indicate if the sample is in the...
In_may_2024_preprint,bool,Whether or not this run was in the May 2024 pr...
Platform,object,instrument_platform from ENA metadata
Region,object,"Region from ENA metadata, if present. If ':' w..."
Run_count,int8,The number of runs from the sample accession
Sample,object,sample_accession from ENA metadata
Study,object,study_accession from ENA metadata
Viridian_N,int16,Number of Ns in the viridian consensus sequenc...
Viridian_amplicon_scheme,object,Amplicon scheme called by Viridian
Viridian_cons_het,int8,
Viridian_cons_len,int16,Length of the Viridian consensus sequence Viri...
Viridian_pangolin,object,Pangolin call from the Viridian consensus sequ...
Viridian_pangolin_1.29,object,Pangolin call from the Viridian consensus sequ...
Viridian_result,object,This is 'PASS' if Viridian finished and made a...
Viridian_scorpio,object,Scorpio call from the Viridian consensus seque...
Viridian_scorpio_1.29,object,Scorpio call from the Viridian consensus seque...

In [4]:
df = ds.metadata.as_dataframe(["Date_tree", "Viridian_scorpio_1.29"])
df

              Date_tree Viridian_scorpio_1.29
sample_id
SRR11772659  2020-01-19                     .
SRR11597132  2020-01-29                     .
SRR12162233  2020-01-30                     .
SRR12162234  2020-01-30                     .
SRR11597217  2020-02-02                     .
...                 ...                   ...
ERR13177478  2023-04-20    Omicron (XBB-like)
ERR13177479  2023-04-21    Omicron (XBB-like)
ERR13177480  2023-04-24    Omicron (XBB-like)
ERR13177481  2023-04-26    Omicron (XBB-like)
ERR13177482  2023-04-27    Omicron (XBB-like)

[4484157 rows x 2 columns]

Filter out incomplete dates for simplicity. Full ISO dates are 10 chars long.

In [7]:
df = df[df["Date_tree"].str.len() == 10]
df

              Date_tree Viridian_scorpio_1.29
sample_id
SRR11772659  2020-01-19                     .
SRR11597132  2020-01-29                     .
SRR12162233  2020-01-30                     .
SRR12162234  2020-01-30                     .
SRR11597217  2020-02-02                     .
...                 ...                   ...
ERR13177478  2023-04-20    Omicron (XBB-like)
ERR13177479  2023-04-21    Omicron (XBB-like)
ERR13177480  2023-04-24    Omicron (XBB-like)
ERR13177481  2023-04-26    Omicron (XBB-like)
ERR13177482  2023-04-27    Omicron (XBB-like)

[4458826 rows x 2 columns]

In [11]:
dfg = df.groupby("Viridian_scorpio_1.29").min()
dfg

                                   Date_tree
Viridian_scorpio_1.29
.                                 2020-01-01
A.23.1-like                       2020-04-12
A.23.1-like+E484K                 2020-12-26
AV.1-like                         2020-12-31
Alpha (B.1.1.7-like)              2020-01-12
B.1.1.318-like                    2020-12-31
B.1.1.7-like+E484K                2020-12-08
B.1.617.1-like                    2020-03-17
B.1.617.3-like                    2020-12-31
Beta (B.1.351-like)               2020-05-27
Delta (AY.4-like)                 2020-10-27
Delta (AY.4.2-like)               2020-12-21
Delta (B.1.617.2-like)            2020-05-08
Delta (B.1.617.2-like) +K417N     2020-12-31
Epsilon (B.1.427-like)            2020-09-17
Epsilon (B.1.429-like)            2020-09-25
Eta (B.1.525-like)                2020-12-15
Gamma (P.1-like)                  2020-05-06
Iota (B.1.526-like)               2020-12-31
Lambda (C.37-like)                2021-01-29
Mu (B.1.621-like)                 2020-12-31
Omicron (BA.1-like)               2020-09-22
Omicron (BA.2-like)               2020-01-10
Omicron (BA.3-like)               2020-12-31
Omicron (BA.4-like)               2020-07-02
Omicron (BA.5-like)               2020-03-31
Omicron (Unassigned)              2020-06-30
Omicron (XBB-like)                2020-10-23
Omicron (XBB.1-like)              2020-12-22
Omicron (XBB.1.16-like)           2020-11-20
Omicron (XBB.1.5-like)            2022-01-17
Omicron (XE-like)                 2022-01-19
Probable Omicron (BA.1-like)      2020-12-31
Probable Omicron (BA.2-like)      2021-12-30
Probable Omicron (BA.3-like)      2022-01-28
Probable Omicron (BA.5-like)      2022-06-11
Probable Omicron (Unassigned)     2020-12-31
Probable Omicron (XBB-like)       2022-10-04
Probable Omicron (XBB.1-like)     2022-12-12
Probable Omicron (XBB.1.16-like)  2023-07-03
Probable Omicron (XBB.1.5-like)   2023-01-07
Theta (P.3-like)                  2021-02-01
Zeta (P.2-like)                   2020-05-04

As a very rough proxy for the existance of time travellers, we just look at the minimum date observed within each of the Scorpio designations. Nearly all of these are post 2020, but yet most have samples in 2020.

In [14]:
dfg_2020 = dfg[dfg["Date_tree"] < "2021"]

In [16]:
dfg_2020.shape

(32, 1)

In [17]:
dfg.shape

(43, 1)

In [18]:
dfg_2020

                                Date_tree
Viridian_scorpio_1.29
.                              2020-01-01
A.23.1-like                    2020-04-12
A.23.1-like+E484K              2020-12-26
AV.1-like                      2020-12-31
Alpha (B.1.1.7-like)           2020-01-12
B.1.1.318-like                 2020-12-31
B.1.1.7-like+E484K             2020-12-08
B.1.617.1-like                 2020-03-17
B.1.617.3-like                 2020-12-31
Beta (B.1.351-like)            2020-05-27
Delta (AY.4-like)              2020-10-27
Delta (AY.4.2-like)            2020-12-21
Delta (B.1.617.2-like)         2020-05-08
Delta (B.1.617.2-like) +K417N  2020-12-31
Epsilon (B.1.427-like)         2020-09-17
Epsilon (B.1.429-like)         2020-09-25
Eta (B.1.525-like)             2020-12-15
Gamma (P.1-like)               2020-05-06
Iota (B.1.526-like)            2020-12-31
Mu (B.1.621-like)              2020-12-31
Omicron (BA.1-like)            2020-09-22
Omicron (BA.2-like)            2020-01-10
Omicron (BA.3-like)            2020-12-31
Omicron (BA.4-like)            2020-07-02
Omicron (BA.5-like)            2020-03-31
Omicron (Unassigned)           2020-06-30
Omicron (XBB-like)             2020-10-23
Omicron (XBB.1-like)           2020-12-22
Omicron (XBB.1.16-like)        2020-11-20
Probable Omicron (BA.1-like)   2020-12-31
Probable Omicron (Unassigned)  2020-12-31
Zeta (P.2-like)                2020-05-04