In [1]:
from collections import Counter
from pathlib import Path
import pandas as pd

In [2]:
data_dir = Path("../data")
overview_file = data_dir / "bigtable_pangodesig.csv"
overview_df = pd.read_csv(overview_file)
pangos = overview_df.pango
len(pangos)

60

#### Independent recombination events

In [3]:
# Get the 1451 independent recombination events from the CovRecomb paper, and
# subset to the ones corresponding to the Pango X labels ("X" series).
# NOTE: No XBB.* or other X?.*
table_s4_url = "https://raw.githubusercontent.com/wuaipinglab/CovRecomb/refs/heads/main/CovRecomb-Global-Version/supplementary%20tables/TableS4.csv"
table_s4_df = pd.read_csv(table_s4_url)
table_s4_df = table_s4_df[table_s4_df.X_series.isin(pangos)].reset_index()
table_s4_df.columns

Index(['index', 'sample_id', 'collect_date', 'pango_lineage', 'lineage_X',
       'lineage_Y', 'mutation_pattern', 'raw_p_value', 'adjusted_p_value',
       'X_mutations', 'Y_mutations', 'shared_mutations', 'denovo_mutations',
       'situation', 'region', 'country', 'Number_of_epidemic_recombinant',
       'Geographical_distribution', 'X_series', 'Confidence_mean',
       'breakpoints'],
      dtype='object')

In [4]:
# Some Pango Xs have multiple events associated with them.
# There is typically one event that has the highest number of epidemic recombinants.
table_s4_df = table_s4_df[
    [
        "X_series",
        "lineage_X",
        "lineage_Y",
        "X_mutations",
        "Y_mutations",
        "mutation_pattern",
        #"situation",
        "breakpoints",
        "Number_of_epidemic_recombinant",
    ]
].sort_values(
    by=["X_series", "Number_of_epidemic_recombinant"],
    ascending=[True, False],
).reset_index(drop=True)
table_s4_df.head(5)

,X_series,lineage_X,lineage_Y,X_mutations,Y_mutations,mutation_pattern,breakpoints,Number_of_epidemic_recombinant
0,XA,B.1.1.7*,B.1.177.18,21765_------/21992_---/23063_T/23271_A/23604_A...,445_C/6286_T/10323_G/21255_C,YYYYXXXXXXXXXXXXXXXXXX,21255-21765,43
1,XAB,BA.1.1*,BA.2.31,2470_T/2832_G/5386_G/6513_---/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,XXXXXYYYYYYYYYYYYYYY,8393-11288,5
2,XAF,BA.1.1.7,BA.2.9*,2470_T/2832_G/5386_G/8393_A,11288_---------/12880_T/15714_T/17410_T/19955_...,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY,8393-11288,427
3,XAF,BA.1.1.7,BA.2.9*,2470_T/2832_G/5386_G/8393_A,11288_---------/12880_T/15714_T/17410_T/21618_...,XXXXYYYYYYYYYYYYYYYYYYYYYYYYYY,8393-11288,2
4,XAG,BA.1.1*,BA.2.9*,2470_T/2832_G/5386_G/6513_---,9534_T/9866_T/10198_T/10447_A/11288_---------/...,XXXXYYYYYYYYYYYYYYYYYYYYYY,6513-9534,17

In [5]:
def _get_breakpoints(mut_patt, left):
    pos = [x.split("_")[0] for x in mut_patt.split("/")]
    if left:
        return pos[0]
    return pos[-1]


data = []
for _, row in table_s4_df.iterrows():
    num_XY = row["mutation_pattern"].count("XY")
    num_YX = row["mutation_pattern"].count("YX")
    if num_XY + num_YX == 1:
        if num_XY == 1:
            parent_left_pango = row["lineage_X"]
            parent_right_pango = row["lineage_Y"]
            interval_left = _get_breakpoints(row["X_mutations"], left=False)
            interval_right = _get_breakpoints(row["Y_mutations"], left=True)
        else:
            parent_left_pango = row["lineage_Y"]
            parent_right_pango = row["lineage_X"]
            interval_left = _get_breakpoints(row["Y_mutations"], left=False)
            interval_right = _get_breakpoints(row["X_mutations"], left=True)
        data.append(
            {
                "pango": row["X_series"],
                "is_in_results": "TRUE",
                "type": "simple",
                "parent_left_pango": parent_left_pango,
                "parent_right_pango": parent_right_pango,
                "interval_left": interval_left,
                "interval_right": interval_right,
                "num_epidemic_recombs": row["Number_of_epidemic_recombinant"],
            }
        )
    else:
        data.append(
            {
                "pango": row["X_series"],
                "is_in_results": "TRUE",
                "type": "complex",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "num_epidemic_recombs": row["Number_of_epidemic_recombinant"],
            }
        )
table_s4_df = pd.DataFrame(data)
table_s4_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,num_epidemic_recombs
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21765,43
1,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11288,5
2,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11288,427
3,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11288,2
4,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9534,17
5,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,43
6,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,15
7,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,6
8,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,2
9,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9344,12
10,XB,TRUE,complex,n/a,n/a,n/a,n/a,3332
11,XB,TRUE,complex,n/a,n/a,n/a,n/a,2
12,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22674,97
13,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22200,7
14,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22786,4
15,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,23019,3
16,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22674,2
17,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24620,268
18,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,22599,24620,3
19,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24620,2
20,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22599,376
21,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26529,8
22,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26529,134
23,XBJ,TRUE,simple,CM.2*,BA.5.2*,22332,26529,2
24,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27972,24
25,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9866,2522
26,XE,TRUE,simple,BA.1.9,BA.2.23,8393,11288,15
27,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288,422
28,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288,5
29,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288,3
30,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15714,73
31,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21618,390
32,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,35
33,XM,TRUE,simple,BA.1.1*,BA.2.23,13195,19955,24
34,XM,TRUE,simple,BA.1.1*,BA.2.23,22194,22688,8
35,XM,TRUE,simple,BA.1.1*,BA.2.23,22194,22688,4
36,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,3
37,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10449,13
38,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10449,2
39,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21618,142

In [6]:
idx = table_s4_df.groupby('pango')['num_epidemic_recombs'].idxmax()
table_s4_df = table_s4_df.loc[idx].reset_index(drop=True)
table_s4_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,num_epidemic_recombs
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21765,43
1,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11288,5
2,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11288,427
3,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9534,17
4,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,43
5,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,2
6,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9344,12
7,XB,TRUE,complex,n/a,n/a,n/a,n/a,3332
8,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22674,97
9,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24620,268
10,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22599,376
11,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26529,8
12,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26529,134
13,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27972,24
14,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9866,2522
15,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288,422
16,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15714,73
17,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21618,390
18,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10449,13
19,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21618,142

#### Other putative recombination events

In [7]:
recomb_url = "https://raw.githubusercontent.com/wuaipinglab/CovRecomb/refs/heads/main/CovRecomb-Global-Version/putative_recombinants/putative%20recombinants.csv"
recomb_df = pd.read_csv(recomb_url)
recomb_df.columns

Index(['sample_id', 'collect_date', 'pango_lineage', 'lineage_X', 'lineage_Y',
       'mutation_pattern', 'raw_p_value', 'adjusted_p_value', 'X_mutations',
       'Y_mutations', 'shared_mutations', 'denovo_mutations', 'region',
       'country'],
      dtype='object')

In [8]:
# NOTE: pango_lineage is the Pango assigned to the sample (from GISAID).
for p in pangos:
    num_pango_lineage = sum(recomb_df.pango_lineage == p)
    #print(p, num_pango_lineage)

In [9]:
data = []
for p in pangos:
    num_simple = 0
    num_complex = 0
    recomb_counts = Counter()
    for _, row in recomb_df[
        # NOTE: Lumps together XBB.* and other X?.*
        (recomb_df.pango_lineage == p) | \
        (recomb_df.pango_lineage.str.startswith(p + "."))
    ].iterrows():
        num_XY = row["mutation_pattern"].count("XY")
        num_YX = row["mutation_pattern"].count("YX")
        if num_XY + num_YX == 1:
            num_simple += 1
            if num_XY == 1:
                parent_left_pango = row["lineage_X"]
                parent_right_pango = row["lineage_Y"]
                interval_left = _get_breakpoints(row["X_mutations"], left=False)
                interval_right = _get_breakpoints(row["Y_mutations"], left=True)
            else:
                parent_left_pango = row["lineage_Y"]
                parent_right_pango = row["lineage_X"]
                interval_left = _get_breakpoints(row["Y_mutations"], left=False)
                interval_right = _get_breakpoints(row["X_mutations"], left=True)
            recomb_counts[(parent_left_pango, parent_right_pango, interval_left, interval_right)] += 1
        else:
            num_complex += 1
    # Summarise results per Pango X.
    if num_simple + num_complex == 0:
        data.append(
            {
                "pango": p,
                "is_in_results": "FALSE",
                "type": "n/a",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "max_count": "n/a",
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
    elif num_simple >= num_complex:
        (
            most_common_parent_left,
            most_common_parent_right,
            most_common_interval_left,
            most_common_interval_right,
        ) = recomb_counts.most_common()[0][0]
        data.append(
            {
                "pango": p,
                "is_in_results": "TRUE",
                "type": "simple",
                "parent_left_pango": most_common_parent_left,
                "parent_right_pango": most_common_parent_right,
                "interval_left": most_common_interval_left,
                "interval_right": most_common_interval_right,
                "max_count": max(recomb_counts.values()),    # Most common
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
    else:
        data.append(
            {
                "pango": p,
                "is_in_results": "TRUE",
                "type": "complex",
                "parent_left_pango": "n/a",
                "parent_right_pango": "n/a",
                "interval_left": "n/a",
                "interval_right": "n/a",
                "max_count": "n/a",
                "num_simple": num_simple,
                "num_complex": num_complex,
            }
        )
recomb_df = pd.DataFrame(data)
recomb_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right,max_count,num_simple,num_complex
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21765,43,43,0
1,XAA,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
2,XAB,TRUE,simple,BA.1.1*,BA.2.31,6513,9344,2,3,0
3,XAC,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
4,XAD,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
5,XAE,TRUE,simple,BA.2.3.16,B.1.1.322,27807,28877,3,3,0
6,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11288,277,292,0
7,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9344,24,38,0
8,XAH,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
9,XAJ,TRUE,complex,n/a,n/a,n/a,n/a,n/a,1,76
10,XAK,TRUE,complex,n/a,n/a,n/a,n/a,n/a,0,28
11,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,94,118,5
12,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9344,11,12,0
13,XAN,TRUE,complex,n/a,n/a,n/a,n/a,n/a,6,13
14,XAP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
15,XAS,TRUE,simple,BA.5,BA.2.17,23075,25416,4,4,2
16,XAU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
17,XAV,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
18,XAY,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
19,XAZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
20,XB,TRUE,complex,n/a,n/a,n/a,n/a,n/a,52,3325
21,XBB,TRUE,simple,BJ.1,BM.1.1.1,22200,22674,46928,51823,758
22,XBC,TRUE,complex,n/a,n/a,n/a,n/a,n/a,5,159
23,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24620,269,273,0
24,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22599,149,156,0
25,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26529,8,8,0
26,XBG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
27,XBH,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
28,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26529,124,134,0
29,XBK,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
30,XBL,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
31,XBM,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
32,XBN,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
33,XBP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
34,XBQ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
35,XBR,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
36,XBS,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
37,XBT,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
38,XBU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
39,XBW,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
40,XBZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
41,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27972,24,24,0
42,XCA,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
43,XCG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
44,XE,TRUE,simple,BA.1.9,BA.2.23,8393,11288,2210,2408,17
45,XF,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
46,XG,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
47,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288,148,159,0
48,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15714,219,247,3
49,XL,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
50,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,19955,273,464,6
51,XN,TRUE,simple,BA.2.3.16,BA.2.69,22688,22792,11,11,0
52,XP,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
53,XQ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
54,XR,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
55,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10449,12,13,0
56,XU,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
57,XW,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0
58,XY,TRUE,simple,BA.1.1*,BA.2.9*,11537,12880,88,117,1
59,XZ,FALSE,n/a,n/a,n/a,n/a,n/a,n/a,0,0

#### Merging the results above

In [10]:
data = []
for p in pangos:
    if any(table_s4_df.pango == p):
        row = table_s4_df[table_s4_df.pango == p]
    else:
        row = recomb_df[recomb_df.pango == p]
    data.append(
        {
            "pango": row["pango"].to_list()[0],
            "is_in_results": row["is_in_results"].to_list()[0],
            "type": row["type"].to_list()[0],
            "parent_left_pango": row["parent_left_pango"].to_list()[0],
            "parent_right_pango": row["parent_right_pango"].to_list()[0],
            "interval_left": row["interval_left"].to_list()[0],
            "interval_right": row["interval_right"].to_list()[0],
        }
    )
merged_df = pd.DataFrame(data)
merged_df

,pango,is_in_results,type,parent_left_pango,parent_right_pango,interval_left,interval_right
0,XA,TRUE,simple,B.1.177.18,B.1.1.7*,21255,21765
1,XAA,FALSE,n/a,n/a,n/a,n/a,n/a
2,XAB,TRUE,simple,BA.1.1*,BA.2.31,8393,11288
3,XAC,FALSE,n/a,n/a,n/a,n/a,n/a
4,XAD,FALSE,n/a,n/a,n/a,n/a,n/a
5,XAE,TRUE,simple,BA.2.3.16,B.1.1.322,27807,28877
6,XAF,TRUE,simple,BA.1.1.7,BA.2.9*,8393,11288
7,XAG,TRUE,simple,BA.1.1*,BA.2.9*,6513,9534
8,XAH,FALSE,n/a,n/a,n/a,n/a,n/a
9,XAJ,TRUE,complex,n/a,n/a,n/a,n/a
10,XAK,TRUE,complex,n/a,n/a,n/a,n/a
11,XAL,TRUE,simple,BA.1.1*,BA.2.23,15240,19955
12,XAM,TRUE,simple,BA.1.1*,BA.2.9*,6513,9344
13,XAN,TRUE,complex,n/a,n/a,n/a,n/a
14,XAP,FALSE,n/a,n/a,n/a,n/a,n/a
15,XAS,TRUE,simple,BA.5,BA.2.17,23075,25416
16,XAU,FALSE,n/a,n/a,n/a,n/a,n/a
17,XAV,FALSE,n/a,n/a,n/a,n/a,n/a
18,XAY,FALSE,n/a,n/a,n/a,n/a,n/a
19,XAZ,FALSE,n/a,n/a,n/a,n/a,n/a
20,XB,TRUE,complex,n/a,n/a,n/a,n/a
21,XBB,TRUE,simple,BJ.1,BM.1.1.1,22109,22674
22,XBC,TRUE,complex,n/a,n/a,n/a,n/a
23,XBD,TRUE,simple,BA.2.75.2*,BF.3.1*,23019,24620
24,XBE,TRUE,simple,BA.5.2.2,BE.4.1.1,21765,22599
25,XBF,TRUE,simple,BM.1.1*,BQ.2,23075,26529
26,XBG,FALSE,n/a,n/a,n/a,n/a,n/a
27,XBH,FALSE,n/a,n/a,n/a,n/a,n/a
28,XBJ,TRUE,simple,CM.2*,BA.5.2*,23013,26529
29,XBK,FALSE,n/a,n/a,n/a,n/a,n/a
30,XBL,FALSE,n/a,n/a,n/a,n/a,n/a
31,XBM,FALSE,n/a,n/a,n/a,n/a,n/a
32,XBN,FALSE,n/a,n/a,n/a,n/a,n/a
33,XBP,FALSE,n/a,n/a,n/a,n/a,n/a
34,XBQ,FALSE,n/a,n/a,n/a,n/a,n/a
35,XBR,FALSE,n/a,n/a,n/a,n/a,n/a
36,XBS,FALSE,n/a,n/a,n/a,n/a,n/a
37,XBT,FALSE,n/a,n/a,n/a,n/a,n/a
38,XBU,FALSE,n/a,n/a,n/a,n/a,n/a
39,XBW,FALSE,n/a,n/a,n/a,n/a,n/a
40,XBZ,FALSE,n/a,n/a,n/a,n/a,n/a
41,XC,TRUE,simple,AY.29.1,B.1.1.7*,26767,27972
42,XCA,FALSE,n/a,n/a,n/a,n/a,n/a
43,XCG,FALSE,n/a,n/a,n/a,n/a,n/a
44,XE,TRUE,simple,BA.1.9,BA.2.23,8393,9866
45,XF,FALSE,n/a,n/a,n/a,n/a,n/a
46,XG,FALSE,n/a,n/a,n/a,n/a,n/a
47,XH,TRUE,simple,BA.1.9,BA.2.9*,8393,11288
48,XJ,TRUE,simple,BA.1.9,BA.2.9*,13195,15714
49,XL,FALSE,n/a,n/a,n/a,n/a,n/a
50,XM,TRUE,simple,BA.1.1*,BA.2.23,15240,21618
51,XN,TRUE,simple,BA.2.3.16,BA.2.69,22688,22792
52,XP,FALSE,n/a,n/a,n/a,n/a,n/a
53,XQ,FALSE,n/a,n/a,n/a,n/a,n/a
54,XR,FALSE,n/a,n/a,n/a,n/a,n/a
55,XS,TRUE,simple,AY.112*,BA.1.1*,9053,10449
56,XU,FALSE,n/a,n/a,n/a,n/a,n/a
57,XW,FALSE,n/a,n/a,n/a,n/a,n/a
58,XY,TRUE,simple,BA.1.1*,BA.2.9*,15240,21618
59,XZ,FALSE,n/a,n/a,n/a,n/a,n/a

In [11]:
csv_file = data_dir / "bigtable_covrecomb.csv"
merged_df.to_csv(csv_file, sep=",", index=False)